### ISSUE TITLE
No matching dist found

### ISSUE THREAD

**Issue by proyb6** [da-coda/mailmon-go#4]
Go get shown it need dist folder but has src folder, manually rename src -> dist fixed it.

**Comment by da-coda** [comment]
Thanks for your Issue report!
MailPie uses the new embed functionality of Go 1.16 for the SPA. Currently I am embedding the dist directory, which locally exists for me, but not within the Git repo. 
It feels kinda dirty to push the dist to the repo, but maybe this is the best way currently, at least for the main branch. 
What do you think?

**Comment by da-coda** [comment]
It should be fixed now. I updated the Github workflow for main to add the dist directory to main. Could you check if it is working now. I was able to reproduce the problem and for me it is now fixed.

**Comment by proyb6** [comment]
Thanks, I intend to run on macOS and it seem isn’t supported or compile except Linux.

**Comment by da-coda** [comment]
AFAIK there should be no code that wouldn't work on unix based systems.
I was able to compile for mac with `GOOS=darwin GOARCH=amd64 go build github.com/da-coda/mailpie .` on my ubuntu. 
What steps did you try? 
What was the output?
Have you installed the 1.16 version of go?

**Comment by da-coda** [comment]
I added my cross compiled version to the release. [Here is the direct download link](https://github.com/da-coda/mailpie/releases/download/v0.2/mailpie_linux_amd64). Could you check if it is running on your machine?

**Comment by da-coda** [comment]
I asked an colleague to install MailPie on his Mac and all seemed fine. He just needed to install the current unstable version of 1.16. You can find it [here](https://golang.org/dl/#go1.16rc1). The 1.16 stable release for go should be this month I think

**Comment by proyb6** [comment]
> I added my cross compiled version to the release. [Here is the direct download link](https://github.com/da-coda/mailpie/releases/download/v0.2/mailpie_linux_amd64). Could you check if it is running on your machine?

Sorry for late reply, I see your binary is ` ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=i0c6hGsgg1z4R9uXLqlL/DqUkZSE7a5O60ngF0knZ/MH0j0Tfeia6A9GHea6ve/4IYZxpUwWCzsimVmQna-, not stripped`

**Comment by da-coda** [comment]
Sorry, stupid me linked the wrong download. https://github.com/da-coda/mailpie/releases/download/v0.2/mailpie_darwin_amd64

**Comment by proyb6** [comment]
I can compile with no issue on Apple M1.
